-- Add Seed Data for Scholarships
INSERT INTO public.scholarships (
    title, category, amount_text, deadline, is_closed, organization, 
    target_summary, description, support_conditions, documents_required, url,
    min_gpa, max_income_bracket, target_grades, target_departments, requires_disability,
    requires_multi_child, requires_national_merit
) VALUES 
(
    '2026학년도 1학기 불교청년지도자 장학금',
    'tuition',
    '등록금 전액',
    '2026-02-15',
    FALSE,
    '대한불교조계종',
    '불교 활동 우수자 및 리더십 보유자',
    '불교 청년 지도자를 양성하기 위한 장학금으로, 교내외 불교 활동 실적이 우수한 학생을 선발합니다.',
    '직전학기 평점 3.0 이상',
    '신청서, 자기소개서, 불교활동증명서, 성적증명서',
    'https://www.buddhism.or.kr',
    3.0, NULL, NULL, NULL, FALSE, FALSE, FALSE
),
(
    '제35기 관정 이종환 교육재단 국내장학생',
    'mixed',
    '학기당 550만원 (최대 4학기)',
    '2026-03-10',
    FALSE,
    '관정 이종환 교육재단',
    '이공계열 우수 학생',
    '대한민국 최우수 이공계 인재를 양성하기 위한 국내 최고 수준의 장학금입니다.',
    '전체 평점 4.0 이상 (4.5 만점 기준)',
    '재학증명서, 성적증명서, 지도교수 추천서, 연구계획서',
    'http://www.ikef.or.kr',
    4.0, NULL, ARRAY[3, 4], ARRAY['컴퓨터공학과', '전자전기공학부', '화공생물공학과', '기계로봇에너지공학과'], FALSE, FALSE, FALSE
),
(
    '2026년 상반기 푸른등대 기부장학금',
    'living',
    '학기당 150만원',
    '2026-01-20',
    FALSE,
    '한국장학재단',
    '저소득층 및 사회배려계층',
    '기부처의 뜻에 따라 다양한 분야의 저소득층 학생을 지원하는 생활비 장학금입니다.',
    '소득구간 3구간 이하',
    '가족관계증명서, 소득구간통지서',
    'https://www.kosaf.go.kr',
    NULL, 3, NULL, NULL, FALSE, FALSE, FALSE
),
(
    '2026 동국건설동문회 장학금',
    'tuition',
    '200만원',
    '2026-01-30',
    FALSE,
    '동국대학교 건설환경공학과 동문회',
    '건설환경공학과 재학생',
    '건설환경공학과 동문회에서 후배들의 학업 증진을 위해 지급하는 장학금입니다.',
    '건설환경공학과 2, 3, 4학년 재학생',
    '장학지원서, 성적증명서',
    NULL,
    2.5, NULL, ARRAY[2, 3, 4], ARRAY['건설환경공학과'], FALSE, FALSE, FALSE
),
(
    '지역인재 육성 장학금 (경기도)',
    'living',
    '연 200만원',
    '2026-02-28',
    FALSE,
    '경기도민장학회',
    '경기도 거주 대학생',
    '경기도에 3년 이상 거주하고 있는 도민의 자녀를 위한 장학금입니다.',
    '직전학기 성적 B학점 이상',
    '주민등록등본, 성적증명서',
    NULL,
    3.0, NULL, NULL, NULL, FALSE, FALSE, FALSE
),
(
    'SW중심대학 마일리지 장학금',
    'mixed',
    '최대 100만원 (마일리지 차등 지급)',
    '2026-02-10',
    FALSE,
    '동국대 SW교육원',
    'SW관련 학과 및 SW연계전공자',
    'SW관련 활동(TOPCIT, 자격증, 해커톤 등) 참여도에 따라 지급되는 마일리지 장학금입니다.',
    'SW중심대학 사업 참여학과 재학생',
    '마일리지 신청서, 증빙서류',
    'https://sw.dongguk.edu',
    NULL, NULL, NULL, ARRAY['컴퓨터공학과', '정보통신공학과', '멀티미디어공학과'], FALSE, FALSE, FALSE
),
(
    '2026 기초수급자 및 차상위계층 희망사다리 장학금',
    'tuition',
    '등록금 전액 + 생활비 20만원',
    '2026-03-15',
    FALSE,
    '교육부',
    '기초생활수급자 및 차상위계층',
    '경제적으로 어려운 학생들도 학업에 전념할 수 있도록 지원하는 국가 장학금입니다.',
    '성적 기준 없음',
    '수급자증명서 또는 차상위계층확인서',
    'https://www.kosaf.go.kr',
    NULL, 1, NULL, NULL, FALSE, FALSE, FALSE
),
(
    '장애대학생 도우미 장학금',
    'living',
    '월 30만원 (근로 연계)',
    '2026-02-25',
    FALSE,
    '동국대 장애학생지원센터',
    '장애학생 도우미 활동 가능자',
    '교내 장애학생의 학습 및 이동을 돕는 도우미 학생에게 지급하는 장학금입니다.',
    '성실하게 활동 가능한 자',
    '근로장학생 신청서',
    NULL,
    NULL, NULL, NULL, NULL, FALSE, FALSE, FALSE
);
